Repository woowa-supp/supp, pull requests merged in 2020-09, with the labels that each got.

#85 refactor : 테스트 코드 작성 및 Controller, Service 리팩토링
  build.gradle
  src/main/java/com/woowa/supp/domain/surveyee/Surveyee.java
  src/main/java/com/woowa/supp/service/SurveyService.java
  src/main/java/com/woowa/supp/web/IndexController.java
  src/main/java/com/woowa/supp/web/SurveyApiController.java
  src/test/java/com/woowa/supp/domain/surveyee/SurveyeeTest.java
  src/test/java/com/woowa/supp/domain/user/UserTest.java
  src/test/java/com/woowa/supp/service/SurveyServiceTest.java
  src/test/java/com/woowa/supp/web/SurveyApiControllerTest.java
Labels: refactor, supp

#88 전역에서 발생하는 예외 처리
  src/main/java/com/woowa/supp/domain/surveyee/DeveloperType.java
  src/main/java/com/woowa/supp/domain/surveyee/SurveyeeRepository.java
  src/main/java/com/woowa/supp/domain/surveyee/style/AfterStudyStyle.java
  src/main/java/com/woowa/supp/domain/surveyee/style/BreaktimeStyle.java
  src/main/java/com/woowa/supp/domain/surveyee/style/ComputerPreferStyle.java
  src/main/java/com/woowa/supp/domain/surveyee/style/InvalidStyleException.java
  src/main/java/com/woowa/supp/domain/surveyee/style/OSStyle.java
  src/main/java/com/woowa/supp/domain/surveyee/style/PairTurnStyle.java
  src/main/java/com/woowa/supp/service/SurveyService.java
  src/main/java/com/woowa/supp/service/UserNotFoundException.java
  src/main/java/com/woowa/supp/web/ControllerAdvice.java
  src/main/java/com/woowa/supp/web/ErrorMessage.java
  src/test/java/com/woowa/supp/domain/surveyee/DeveloperTypeTest.java
  src/test/java/com/woowa/supp/domain/surveyee/style/AfterStudyStyleTest.java
  src/test/java/com/woowa/supp/domain/surveyee/style/BreaktimeStyleTest.java
  src/test/java/com/woowa/supp/domain/surveyee/style/ComputerPreferStyleTest.java
  src/test/java/com/woowa/supp/domain/surveyee/style/OSStyleTest.java
  src/test/java/com/woowa/supp/domain/surveyee/style/PairTurnStyleTest.java
  src/test/java/com/woowa/supp/service/SurveyServiceTest.java
Labels: feature

#89 스프링 부트 버전 변경 및 의존성 정리
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: refactor
